name: Docs
description: ドキュメント整備
labels: [docs]
body:
  - type: input
    id: title
    attributes:
      label: タイトル（1行）
      placeholder: 例）README に起動手順を追記
    validations:
      required: true
  - type: textarea
    id: scope
    attributes:
      label: 範囲
      placeholder: どのドキュメント・どの章か

