name: Long-term Discussion
description: 長期的な議論・検討が必要なトピック（設計方針、アーキテクチャ検討など）
labels: [discussion]
body:
  - type: input
    id: summary
    attributes:
      label: 概要（1行）
      placeholder: 例）ユーザー認証システムの設計方針検討
    validations:
      required: true
  - type: textarea
    id: background
    attributes:
      label: 背景・課題
      placeholder: なぜこの議論が必要なのか、現在の課題や検討の背景を記載
    validations:
      required: true
  - type: textarea
    id: discussion_points
    attributes:
      label: 議論したいポイント
      placeholder: |
        - 検討したい観点1
        - 検討したい観点2
        - 検討したい観点3
        
        具体的な質問や論点を箇条書きで記載
    validations:
      required: true
  - type: textarea
    id: current_ideas
    attributes:
      label: 現時点でのアイデア・候補
      placeholder: |
        既に考えているアプローチや選択肢があれば記載
        - 案1：詳細
        - 案2：詳細
  - type: dropdown
    id: priority
    attributes:
      label: 優先度
      options:
        - 高（緊急に決める必要がある）
        - 中（次のスプリントまでに決めたい）
        - 低（長期的に検討していく）
    validations:
      required: true
  - type: textarea
    id: timeline
    attributes:
      label: 想定スケジュール
      placeholder: |
        いつまでに何を決めたいか
        例）
        - 1週間後：基本方針決定
        - 2週間後：詳細設計完了
        - 3週間後：実装開始
  - type: textarea
    id: decision_criteria
    attributes:
      label: 意思決定の基準
      placeholder: |
        どういう観点で最終決定するか
        例）パフォーマンス、保守性、開発速度、コスト など
  - type: textarea
    id: next_actions
    attributes:
      label: 次のアクション
      placeholder: |
        この議論を進めるために必要なアクション
        - [ ] 調査タスク1
        - [ ] 調査タスク2
        - [ ] プロトタイプ作成
